In [ ]:
import pandas as pd
import numpy as np

df = pd.read_excel('/content/03 Diversity-Inclusion-Dataset.xlsx', sheet_name = 'Pharma Group AG')
df.head()

,Employee ID,Gender,Job Level after FY20 promotions,New hire FY20?,FY20 Performance Rating,Promotion in FY21?,In base group for Promotion FY21,Target hire balance,FY20 leaver?,In base group for turnover FY20,...,Promotion in FY20?,FY19 Performance Rating,Age group,Age @01.07.2020,Nationality 1,Region group: nationality 1,Broad region group: nationality 1,Last hire date,Years since last hire,Rand
0,1,Male,6 - Junior Officer,N,2.0,No,No,0.5,Yes,Y,...,N,3.0,30 to 39,37,Spain,Europe,Europe,2017-04-01,3,0.177804
1,2,Female,4 - Manager,N,3.0,No,Yes,0.5,No,Y,...,N,NaN,30 to 39,37,Germany,Europe,Europe,2017-04-01,3,0.579315
2,3,Male,2 - Director,N,2.0,No,Yes,0.5,No,Y,...,N,3.0,30 to 39,35,Switzerland,Switzerland,Switzerland,2015-04-01,5,0.887683
3,4,Male,4 - Manager,N,3.0,No,Yes,0.5,No,Y,...,N,3.0,30 to 39,32,Germany,Europe,Europe,2012-04-01,8,0.053887
4,5,Female,6 - Junior Officer,N,2.0,No,Yes,0.5,No,Y,...,N,NaN,20 to 29,28,Switzerland,Switzerland,Switzerland,2019-04-01,1,0.971681

In [ ]:
replacement = {
    "1 - Executive": 1,
    "2 - Director" : 2,
    "3 - Senior Manager" : 3,
    "4 - Manager" :  4,
    "5 - Senior Officer" : 5,
    "6 - Junior Officer": 6
}

df = df[[
    'Employee ID',
    'Job Level before FY20 promotions',
    'Job Level after FY20 promotions',
    'Job Level after FY21 promotions',
    'Gender'
]].set_index('Employee ID')



df['Job Level before FY20 promotions'] = df['Job Level before FY20 promotions'].fillna(99)
df['Job Level after FY21 promotions'] = df['Job Level after FY21 promotions'].fillna(99)

target_cols = ['Job Level before FY20 promotions','Job Level after FY20 promotions','Job Level after FY21 promotions']

for col in target_cols :
  df[col] = df[col].replace(replacement)

In [ ]:
df['Maximum job position reached'] = df[target_cols].min(axis = 1).replace({list(replacement.values())[i] : list(replacement.keys())[i] for i in range(6)})

In [ ]:
df.to_csv('maximum_pos.csv')